### ISSUE TITLE
After generating shortened url how redirecting to original link is done 

### ISSUE THREAD

**Issue by mahesh-1998** [cdvel/url-shortenr#1]
![Screenshot from 2020-03-13 11-20-51](https://user-images.githubusercontent.com/40057902/76593618-d4afc480-651c-11ea-9412-4ef938acbd2b.png)

**Comment by cdvel** [comment]
make sure to `firebase deploy --only functions` via CLI

The redirect happens at https://github.com/cdvel/url-shortenr/blob/master/functions/src/index.ts
